### ISSUE TITLE
在第一个温窗测量一组数据后报错

### ISSUE THREAD

**Issue by linncy** [linncy/TesterAutomation-TCf#1]
目前使用了三个线程分别用于：
线程1：温控仪指令数据发送\读取
线程2：LRC测试仪控制指令数据发送\读取
线程3：UI线程更新UI\图像\数据点\ProgressBar

考虑线程1与线程2存在同时发送\读取的可能性，造成GPIB通信冲突

**Comment by nano-desu** [comment]
同时发送读取有两种思路：
1.线程间同步
2.在进行扫描时关闭温度实时读取，在读取LRC读数时在该线程内同步进行温度数据的读取。（目前已经实现的应急措施）
